name: queuenode

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: pnpm run dev:server
    env_file:
      - .env
    networks:
      - queuenode-network
    healthcheck:
      test: ["CMD", "curl -f http://localhost:3333/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  queue:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: pnpm run dev:queue
    env_file:
      - .env
    networks:
      - queuenode-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'pnpm run dev:queue' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - queuenode-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  redis-data:
    driver: local

networks:
  queuenode-network:
    driver: bridge